apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: jenkins
    server: https://kubernetes.default.svc
  project: tools
  source:
    path: charts/jenkins
    repoURL: https://github.com/jenkinsci/helm-charts.git
    targetRevision: master
    # helm:
    #   values: |
    #     master:
    #       ingress:
    #         enabled: true
    #         hostName: jenkins.demo.atoy.dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
