apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umbrella-app
  namespace: kube-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: resources/
    repoURL: https://github.com/alterus-io/demo-app.git
    targetRevision: master