apiVersion: cert-manager.io/v1beta1
kind: Issuer
metadata:
  name: argocd-issuer
  namespace: kube-system
spec:
  acme:
    email: atoy3731@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: traefik
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: kube-system
  annotations:
    cert-manager.io/issuer: argocd-issuer
    cert-manager.io/issuer-kind: Issuer
spec:
  rules:
    - host: "argo.demo.alterus.io"
      http:
        paths:
          - path: /
            backend:
              serviceName: argocd-server
              servicePort: 80
  tls:
  - hosts:
    - argo.demo.alterus.io
    secretName: tls-argo-ingress


