apiVersion: cert-manager.io/v1beta1
kind: ClusterIssuer
metadata:
  name: demo-issuer
  namespace: kube-system
spec:
  acme:
    email: atoy3731@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: traefik