apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: demo-issuer
spec:
  rules:
    - host: {{ .Values.argoHost }}
      http:
        paths:
          - path: /
            backend:
              serviceName: argocd-server
              servicePort: 80
  tls:
  - hosts:
    - {{ .Values.argoHost }}
    secretName: {{ .Values.argoTlsSecret }}


