apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sonarqube-ingress
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: demo-issuer
    {{- if .Values.httpsRedirect }}
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    {{- end }}
spec:
  rules:
    - host: {{ .Values.sonarqubeHost }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.sonarqubeService.name }}
              servicePort: {{ .Values.sonarqubeService.port }}
  tls:
  - hosts:
    - {{ .Values.sonarqubeHost }}
    secretName: {{ .Values.sonarqubeTlsSecret }}


